GET http://localhost:3000/books HTTP/1.1

###
GET http://localhost:3000/books/2 HTTP/1.1

###
POST http://localhost:3000/books HTTP/1.1
Content-Type: application/json

{
    "name": "fromis_9",
    "members": 9,
    "debut": 2017
}

###
PUT http://localhost:3000/books/3 HTTP/1.1
Content-Type: application/json

{
    "name": "fromis_9",
    "members": 8,
    "debut": 2017
}